apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"railsapp"},"name":"railsapp","namespace":"hyrax"},"spec":{"ports":[{"name":"3000-tcp","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"railsapp","deploymentconfig":"railsapp"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: railsapp
    name: railsapp
  spec:
    ports:
    - name: 3000-tcp
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: railsapp
      deploymentconfig: railsapp
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 60s
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Route","metadata":{"annotations":{"openshift.io/host.generated":"true"},"creationTimestamp":null,"labels":{"app":"railsapp"},"name":"hyrax-application-route","namespace":"hyrax"},"spec":{"host":"hyrax-application-route-hyrax.192.168.99.100.nip.io","port":{"targetPort":"3000-tcp"},"to":{"kind":"Service","name":"railsapp","weight":100},"wildcardPolicy":"None"},"status":{"ingress":[{"conditions":[{"lastTransitionTime":"2017-10-19T18:30:51Z","status":"True","type":"Admitted"}],"host":"hyrax-application-route-hyrax.192.168.99.100.nip.io","routerName":"router","wildcardPolicy":"None"}]}}
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: railsapp
    name: hyrax-application-route
  spec:
    host: hyrax-application-route-hyrax.192.168.99.100.nip.io
    port:
      targetPort: 3000-tcp
    to:
      kind: Service
      name: railsapp
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2017-10-20T20:13:13Z
        status: "True"
        type: Admitted
      host: hyrax-application-route-hyrax.192.168.99.100.nip.io
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ImageStream","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"generation":1,"labels":{"app":"railsapp"},"name":"railsapp","namespace":"hyrax"},"spec":{"lookupPolicy":{"local":false}},"status":{"dockerImageRepository":""}}
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: railsapp
    name: railsapp
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/hyrax/railsapp:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"BuildConfig","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"railsapp"},"name":"railsapp","namespace":"hyrax"},"spec":{"failedBuildsHistoryLimit":5,"nodeSelector":null,"output":{"to":{"kind":"ImageStreamTag","name":"railsapp:latest"}},"resources":{},"runPolicy":"Serial","source":{"git":{"ref":"master","uri":"https://github.com/samvera/hyrax.git"},"type":"Git"},"strategy":{"sourceStrategy":{"env":[{"name":"RAILS_ENV","value":"development"}],"from":{"kind":"ImageStreamTag","name":"ruby:2.3","namespace":"openshift"}},"type":"Source"},"successfulBuildsHistoryLimit":5,"triggers":[{"github":{"secret":"BJS1x47K1VN8piPbfCwR"},"type":"GitHub"},{"generic":{"secret":"Ju1UWW87Q7EQMoatuJ6M"},"type":"Generic"},{"type":"ConfigChange"},{"imageChange":{},"type":"ImageChange"}]},"status":{"lastVersion":0}}
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: railsapp
    name: railsapp
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: railsapp:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/samvera/hyrax.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: RAILS_ENV
          value: development
        from:
          kind: ImageStreamTag
          name: ruby:2.3
          namespace: openshift
        scripts: https://raw.githubusercontent.com/ndlib/oshifted_hyrax/master/.s2i/bin/
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: BJS1x47K1VN8piPbfCwR
      type: GitHub
    - generic:
        secret: Ju1UWW87Q7EQMoatuJ6M
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"DeploymentConfig","metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"generation":1,"labels":{"app":"railsapp"},"name":"railsapp","namespace":"hyrax"},"spec":{"replicas":1,"selector":{"app":"railsapp","deploymentconfig":"railsapp"},"strategy":{"activeDeadlineSeconds":21600,"resources":{},"rollingParams":{"intervalSeconds":1,"maxSurge":"25%","maxUnavailable":"25%","timeoutSeconds":600,"updatePeriodSeconds":1},"type":"Rolling"},"template":{"metadata":{"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"},"creationTimestamp":null,"labels":{"app":"railsapp","deploymentconfig":"railsapp"}},"spec":{"containers":[{"env":[{"name":"SECRET_KEY_BASE","value":"86c866f84b4db49487a2d7244c9c8567ef7982ad3a89a3e711ad969a28eee2589eed52b6d81ebe2e62be1ee58b2ef0709011e28dc907ff3ef3d252e1e608a970"},{"name":"RAILS_ENV","value":"development"},{"name":"SOLR_URL","value":"http://10.41.58.226:8983/solr/hydra-development/"},{"name":"SOLR_DEV_HOST","value":"10.41.58.226"},{"name":"SOLR_DEV_PORT","value":"8983"},{"name":"FCREPO_DEV_HOST","value":"10.41.58.226"},{"name":"FCREPO_DEV_PORT","value":"8984"},{"name":"REDIS_HOST","value":"10.41.58.226"},{"name":"REDIS_PORT","value":"6379"}],"image":"railsapp:latest","imagePullPolicy":"Always","name":"railsapp","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["railsapp"],"from":{"kind":"ImageStreamTag","name":"railsapp:latest","namespace":"hyrax"}},"type":"ImageChange"}]},"status":{"availableReplicas":0,"latestVersion":0,"observedGeneration":0,"replicas":0,"unavailableReplicas":0,"updatedReplicas":0}}
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: railsapp
    name: railsapp
  spec:
    replicas: 1
    selector:
      app: railsapp
      deploymentconfig: railsapp
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: railsapp
          deploymentconfig: railsapp
      spec:
        containers:
        - env:
          - name: SECRET_KEY_BASE
            value: 86c866f84b4db49487a2d7244c9c8567ef7982ad3a89a3e711ad969a28eee2589eed52b6d81ebe2e62be1ee58b2ef0709011e28dc907ff3ef3d252e1e608a970
          - name: RAILS_ENV
            value: development
          - name: SOLR_URL
            value: http://10.41.58.226:8983/solr/hydra-development/
          - name: FCREPO_DEV_HOST
            value: 10.41.58.226
          - name: FCREPO_DEV_PORT
            value: "8984"
          - name: SOLR_DEV_HOST
            value: 10.41.58.226
          - name: SOLR_DEV_PORT
            value: "8983"
          - name: REDIS_HOST
            value: 10.41.58.226
          - name: REDIS_PORT
            value: '6379'
          image: railsapp:latest
          imagePullPolicy: Always
          name: railsapp
          ports:
          - containerPort: 3000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - railsapp
        from:
          kind: ImageStreamTag
          name: railsapp:latest
          namespace: hyrax
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
